### ISSUE TITLE
Sessions are not deleted from the list when we erase a oauth2 authorized application

### ISSUE THREAD

**Issue by davitol** [owncloud/oauth2#125]
### Steps to reproduce
1. As admin User enable Oauth2 in your server
2. Using a mobile device log in using oauth
3. Log in the webUI and delete Android Client as Authorized Applications

(the steps to reproduce flow is shown in the following gif)

![hola](https://user-images.githubusercontent.com/10596560/37761495-20bc7266-2dba-11e8-9493-d699ced9b3f0.gif)

### Expected behaviour

The sessions should be removed from the list.

### Actual behaviour

The session are kept shown in the list even when the user is logged out from his session in the mobile device

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:" ownCloud Stable10 from 20 March 2018 and oauth2 app from release/0.2.2 branch

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"RIDnfyWgguTLhS6gdYGF","level":3,"time":"2018-03-22T09:11:50+00:00","remoteAddr":"85.57.168.79","user":"--","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"Exception: Invalid token at \/opt\/owncloud\/apps\/oauth2\/lib\/AuthModule.php#53"}
{"reqId":"9bxSMGBIyk9kwjd5KoYB","level":3,"time":"2018-03-22T09:11:50+00:00","remoteAddr":"85.57.168.79","user":"--","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/cloud\/user?format=json","message":"Exception: Invalid token at \/opt\/owncloud\/apps\/oauth2\/lib\/AuthModule.php#53"}
{"reqId":"TlGLvy0nw14Ol6DyUchU","level":3,"time":"2018-03-22T09:11:50+00:00","remoteAddr":"85.57.168.79","user":"--","app":"OCA\\OAuth2\\Controller\\OAuthApiController","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"Did expect one result but found none when executing: query \\\"SELECT * FROM `*PREFIX*oauth2_refresh_tokens` WHERE `token` = ?\\\"; parameters Array\\n(\\n    [0] => 8kb6J3lgKkfAAbTS5aBxohAvQULSvKgOZ3VZZdwZpdHqyDhnMAHjypv232fKnDVa\\n)\\n; limit \\\"\\\"; offset \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(379): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Db\\\/RefreshTokenMapper.php(75): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array, NULL, NULL)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Controller\\\/OAuthApiController.php(165): OCA\\\\OAuth2\\\\Db\\\\RefreshTokenMapper->findByToken('8kb6J3lgKkfAAbT...')\\n#3 [internal function]: OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController->generateToken(*** sensitive parameters replaced ***)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController), 'generateToken')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController), 'generateToken')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\OAuth2\\\\\\\\Cont...', 'generateToken', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/apps\\\/oauth2\\\/ap...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php\",\"Line\":294}"}
{"reqId":"IRtR5hH0Gc7UmSSBKzbt","level":3,"time":"2018-03-22T09:11:51+00:00","remoteAddr":"85.57.168.79","user":"--","app":"OCA\\OAuth2\\Controller\\OAuthApiController","method":"POST","url":"\/index.php\/apps\/oauth2\/api\/v1\/token","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"Did expect one result but found none when executing: query \\\"SELECT * FROM `*PREFIX*oauth2_refresh_tokens` WHERE `token` = ?\\\"; parameters Array\\n(\\n    [0] => 8kb6J3lgKkfAAbTS5aBxohAvQULSvKgOZ3VZZdwZpdHqyDhnMAHjypv232fKnDVa\\n)\\n; limit \\\"\\\"; offset \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(379): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Db\\\/RefreshTokenMapper.php(75): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array, NULL, NULL)\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/oauth2\\\/lib\\\/Controller\\\/OAuthApiController.php(165): OCA\\\\OAuth2\\\\Db\\\\RefreshTokenMapper->findByToken('8kb6J3lgKkfAAbT...')\\n#3 [internal function]: OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController->generateToken(*** sensitive parameters replaced ***)\\n#4 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#5 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController), 'generateToken')\\n#6 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\OAuth2\\\\Controller\\\\OAuthApiController), 'generateToken')\\n#7 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\OAuth2\\\\\\\\Cont...', 'generateToken', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/opt\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/apps\\\/oauth2\\\/ap...')\\n#11 \\\/opt\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php\",\"Line\":294}"}
```

### Client configuration

**browser**

Firefox

**Comment by davitol** [comment]
Closed, Dupe of https://github.com/owncloud/oauth2/issues/103
