### ISSUE TITLE
UniqueConstraintViolationException when logging in two phoenix session from same user

### ISSUE THREAD

**Issue by individual-it** [owncloud/oauth2#227]
### Steps to reproduce
1. login with phoenix in browser1
2. login with phoenix in browser2 (or separated tab) as the same user 
3. check the logs

### Expected behaviour
no "bad" log messages

### Actual behaviour
```
{"reqId":"jKfEFX9z2SNRRKLZ9IJj","level":3,"time":"2019-10-15T06:04:43+00:00","remoteAddr":"192.168.1.10","user":"admin","app":"OC\\User\\Session::createSessionToken","method":"GET","url":"\/owncloud-core\/\/remote.php\/dav\/avatars\/admin\/128.png","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_authtoken`(`uid`,`login_name`,`name`,`token`,`type`,`last_activity`,`last_check`) VALUES(?,?,?,?,?,?,?)' with params [\\\"admin\\\", \\\"admin\\\", \\\"Mozilla\\\\\\\/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko\\\\\\\/20100101 Firefox\\\\\\\/69.0\\\", \\\"2eb0c411103f0f6c14f9c0d562564f91f1b90ea727cdea1c90a16c99d8a0d89a58c9f3575f82a6b286d8c631373d13611675f4d277ce9eb995d02fc5a1571936\\\", 0, 1571119483, 1571119483]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2eb0c411103f0f6c14f9c0d562564f91f1b90ea727cdea1c90a16c99d8a0d89a' for key 'authtoken_token_index'\",\"Code\":0,\"Trace\":\"
#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))
#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)
#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(241): Doctrine\\\\DBAL\\\\Statement->execute()
#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(119): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)
#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(101): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))
#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(725): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)
#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(974): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'admin', 'admin', NULL)
#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/OAuth2.php(120): OC\\\\User\\\\Session->tryAuthModuleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))
#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/AbstractBearer.php(99): OCA\\\\OAuth2\\\\Sabre\\\\OAuth2->validateBearerToken('At4PfI0P5VQ6CgP...')
#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(193): OCA\\\\OAuth2\\\\Sabre\\\\AbstractBearer->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(144): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(448): Sabre\\\\DAV\\\\Server->emit('beforeMethod:GE...', Array)
#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#14 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()
#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()
#16 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(165): require_once('\\\/home\\\/artur\\\/www...')
#17 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}"}
{"reqId":"jKfEFX9z2SNRRKLZ9IJj","level":3,"time":"2019-10-15T06:04:43+00:00","remoteAddr":"192.168.1.10","user":"admin","app":"OC\\User\\Session::createSessionToken","method":"GET","url":"\/owncloud-core\/\/remote.php\/dav\/avatars\/admin\/128.png","message":"Caused by: {\"Exception\":\"Doctrine\\\\DBAL\\\\Driver\\\\PDOException\",\"Message\":\"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2eb0c411103f0f6c14f9c0d562564f91f1b90ea727cdea1c90a16c99d8a0d89a' for key 'authtoken_token_index'\",\"Code\":\"23000\",\"Trace\":\"
#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(168): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute(NULL)
#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(241): Doctrine\\\\DBAL\\\\Statement->execute()
#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(119): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)
#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(101): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))
#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(725): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)
#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(974): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'admin', 'admin', NULL)
#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/OAuth2.php(120): OC\\\\User\\\\Session->tryAuthModuleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))
#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/AbstractBearer.php(99): OCA\\\\OAuth2\\\\Sabre\\\\OAuth2->validateBearerToken('At4PfI0P5VQ6CgP...')
#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(193): OCA\\\\OAuth2\\\\Sabre\\\\AbstractBearer->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(144): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(448): Sabre\\\\DAV\\\\Server->emit('beforeMethod:GE...', Array)
#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()
#14 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()
#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(165): require_once('\\\/home\\\/artur\\\/www...')
#16 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php\",\"Line\":107}"}
{"reqId":"jKfEFX9z2SNRRKLZ9IJj","level":3,"time":"2019-10-15T06:04:43+00:00","remoteAddr":"192.168.1.10","user":"admin","app":"OC\\User\\Session::createSessionToken","method":"GET","url":"\/owncloud-core\/\/remote.php\/dav\/avatars\/admin\/128.png","message":"Caused by: {\"Exception\":\"PDOException\",\"Message\":\"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2eb0c411103f0f6c14f9c0d562564f91f1b90ea727cdea1c90a16c99d8a0d89a' for key 'authtoken_token_index'\",\"Code\":\"23000\",\"Trace\":\"
#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(168): Doctrine\\\\DBAL\\\\Driver\\\\PDOStatement->execute(NULL)
#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(241): Doctrine\\\\DBAL\\\\Statement->execute()
#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(119): OCP\\\\AppFramework\\\\Db\\\\Mapper->execute('INSERT INTO `*P...', Array)
#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/Authentication\\\/Token\\\/DefaultTokenProvider.php(101): OCP\\\\AppFramework\\\\Db\\\\Mapper->insert(Object(OC\\\\Authentication\\\\Token\\\\DefaultToken))
#5 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(725): OC\\\\Authentication\\\\Token\\\\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)
#6 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/private\\\/User\\\/Session.php(974): OC\\\\User\\\\Session->createSessionToken(Object(OC\\\\AppFramework\\\\Http\\\\Request), 'admin', 'admin', NULL)
#7 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/OAuth2.php(120): OC\\\\User\\\\Session->tryAuthModuleLogin(Object(OC\\\\AppFramework\\\\Http\\\\Request))
#8 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/oauth2\\\/lib\\\/Sabre\\\/AbstractBearer.php(99): OCA\\\\OAuth2\\\\Sabre\\\\OAuth2->validateBearerToken('At4PfI0P5VQ6CgP...')
#9 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(193): OCA\\\\OAuth2\\\\Sabre\\\\AbstractBearer->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#10 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(144): Sabre\\\\DAV\\\\Auth\\\\Plugin->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#11 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#12 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(448): Sabre\\\\DAV\\\\Server->emit('beforeMethod:GE...', Array)
#13 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))
#14 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()
#15 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()
#16 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(165): require_once('\\\/home\\\/artur\\\/www...')
#17 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/PDOStatement.php\",\"Line\":105}"}
```

**Comment by butonic** [comment]
This is a TODO to debug the code paths that can cause this: we are actually catching the exception in https://github.com/owncloud/core/blob/8c5e5fb37b31b45c88275304c8033b57a04fbf1d/lib/private/User/Session.php#L757

To gather more details on the token use a conditional log as described in https://github.com/owncloud/core/pull/31460#issue-323948177

**Comment by butonic** [comment]
tracked as core issue https://github.com/owncloud/core/issues/34524
